name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  nix-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v15
        with:
          name: logos-co
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and run tests (flake check)
        run: nix build .#checks.x86_64-linux.tests -L
